// REGISTER
export const CONSULT_REGISTER_REQUEST = "CONSULT_REGISTER_REQUEST";
export const CONSULT_REGISTER_SUCESS = "CONSULT_REGISTER_SUCESS";
export const CONSULT_REGISTER_FAIL = "CONSULT_REGISTER_FAIL";
export const CONSULT_REGISTER_RESET = "CONSULT_REGISTER_RESET";

// LIST
export const CONSULT_LIST_REQUEST = "CONSULT_LIST_REQUEST";
export const CONSULT_LIST_SUCESS = "CONSULT_LIST_SUCESS";
export const CONSULT_LIST_FAIL = "CONSULT_LIST_FAIL";
export const CONSULT_LIST_RESET = "CONSULT_LIST_RESET";

// UPDATE
export const CONSULT_UPDATE_REQUEST = "CONSULT_UPDATE_REQUEST";
export const CONSULT_UPDATE_SUCESS = "CONSULT_UPDATE_SUCESS";
export const CONSULT_UPDATE_FAIL = "CONSULT_UPDATE_FAIL";
export const CONSULT_UPDATE_RESET = "CONSULT_UPDATE_RESET";

// DETAILS
export const CONSULT_DETAILS_REQUEST = "CONSULT_DETAILS_REQUEST";
export const CONSULT_DETAILS_SUCESS = "CONSULT_DETAILS_SUCESS";
export const CONSULT_DETAILS_FAIL = "CONSULT_DETAILS_FAIL";
export const CONSULT_DETAILS_RESET = "CONSULT_DETAILS_RESET";
// DELETE
export const CONSULT_DELETE_REQUEST = "CONSULT_DELETE_REQUEST";
export const CONSULT_DELETE_SUCESS = "CONSULT_DELETE_SUCESS";
export const CONSULT_DELETE_FAIL = "CONSULT_DELETE_FAIL";
export const CONSULT_DELETE_RESET = "CONSULT_DELETE_RESET";
// HISTORY
export const CONSULT_HISTORY_REQUEST = "CONSULT_HISTORY_REQUEST";
export const CONSULT_HISTORY_SUCESS = "CONSULT_HISTORY_SUCESS";
export const CONSULT_HISTORY_FAIL = "CONSULT_HISTORY_FAIL";
export const CONSULT_HISTORY_RESET = "CONSULT_HISTORY_RESET";
