// REGISTER
export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST";
export const PATIENT_REGISTER_SUCESS = "PATIENT_REGISTER_SUCESS";
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL";
export const PATIENT_REGISTER_RESET = "PATIENT_REGISTER_RESET";

// LIST
export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCESS = "PATIENT_LIST_SUCESS";
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL";
export const PATIENT_LIST_RESET = "PATIENT_LIST_RESET";

// UPDATE
export const PATIENT_UPDATE_REQUEST = "PATIENT_UPDATE_REQUEST";
export const PATIENT_UPDATE_SUCESS = "PATIENT_UPDATE_SUCESS";
export const PATIENT_UPDATE_FAIL = "PATIENT_UPDATE_FAIL";
export const PATIENT_UPDATE_RESET = "PATIENT_UPDATE_RESET";

// DETAILS
export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST";
export const PATIENT_DETAILS_SUCESS = "PATIENT_DETAILS_SUCESS";
export const PATIENT_DETAILS_FAIL = "PATIENT_DETAILS_FAIL";
export const PATIENT_DETAILS_RESET = "PATIENT_DETAILS_RESET";
// DELETE
export const PATIENT_DELETE_REQUEST = "PATIENT_DELETE_REQUEST";
export const PATIENT_DELETE_SUCESS = "PATIENT_DELETE_SUCESS";
export const PATIENT_DELETE_FAIL = "PATIENT_DELETE_FAIL";
export const PATIENT_DELETE_RESET = "PATIENT_DELETE_RESET";
// SEARCH
export const PATIENT_SEARCH_REQUEST = "PATIENT_SEARCH_REQUEST";
export const PATIENT_SEARCH_SUCESS = "PATIENT_SEARCH_SUCESS";
export const PATIENT_SEARCH_FAIL = "PATIENT_SEARCH_FAIL";
export const PATIENT_SEARCH_RESET = "PATIENT_SEARCH_RESET";
