// REGISTER
export const SERVICE_REGISTER_REQUEST = "SERVICE_REGISTER_REQUEST";
export const SERVICE_REGISTER_SUCESS = "SERVICE_REGISTER_SUCESS";
export const SERVICE_REGISTER_FAIL = "SERVICE_REGISTER_FAIL";
export const SERVICE_REGISTER_RESET = "SERVICE_REGISTER_RESET";

// LIST
export const SERVICE_LIST_REQUEST = "SERVICE_LIST_REQUEST";
export const SERVICE_LIST_SUCESS = "SERVICE_LIST_SUCESS";
export const SERVICE_LIST_FAIL = "SERVICE_LIST_FAIL";
export const SERVICE_LIST_RESET = "SERVICE_LIST_RESET";

// UPDATE
export const SERVICE_UPDATE_REQUEST = "SERVICE_UPDATE_REQUEST";
export const SERVICE_UPDATE_SUCESS = "SERVICE_UPDATE_SUCESS";
export const SERVICE_UPDATE_FAIL = "SERVICE_UPDATE_FAIL";
export const SERVICE_UPDATE_RESET = "SERVICE_UPDATE_RESET";

// DETAILS
export const SERVICE_DETAILS_REQUEST = "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCESS = "SERVICE_DETAILS_SUCESS";
export const SERVICE_DETAILS_FAIL = "SERVICE_DETAILS_FAIL";
export const SERVICE_DETAILS_RESET = "SERVICE_DETAILS_RESET";

// DELETE
export const SERVICE_DELETE_REQUEST = "SERVICE_DELETE_REQUEST";
export const SERVICE_DELETE_SUCESS = "SERVICE_DELETE_SUCESS";
export const SERVICE_DELETE_FAIL = "SERVICE_DELETE_FAIL";
export const SERVICE_DELETE_RESET = "SERVICE_DELETE_RESET";