// REGISTER
export const SERVICE_CREATE_REQUEST = "SERVICE_CREATE_REQUEST";
export const SERVICE_CREATE_SUCESS = "SERVICE_CREATE_SUCESS";
export const SERVICE_CREATE_FAIL = "SERVICE_CREATE_FAIL";
export const SERVICE_CREATE_RESET = "SERVICE_CREATE_RESET";

// LIST
export const SERVICE_LIST_REQUEST = "SERVICE_LIST_REQUEST";
export const SERVICE_LIST_SUCESS = "SERVICE_LIST_SUCESS";
export const SERVICE_LIST_FAIL = "SERVICE_LIST_FAIL";
export const SERVICE_LIST_RESET = "SERVICE_LIST_RESET";

// UPDATE
export const SERVICE_UPDATE_REQUEST = "SERVICE_UPDATE_REQUEST";
export const SERVICE_UPDATE_SUCESS = "SERVICE_UPDATE_SUCESS";
export const SERVICE_UPDATE_FAIL = "SERVICE_UPDATE_FAIL";
export const SERVICE_UPDATE_RESET = "SERVICE_UPDATE_RESET";

// DETAILS
export const SERVICE_DETAILS_REQUEST = "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCESS = "SERVICE_DETAILS_SUCESS";
export const SERVICE_DETAILS_FAIL = "SERVICE_DETAILS_FAIL";
export const SERVICE_DETAILS_RESET = "SERVICE_DETAILS_RESET";