# Generated by Django 3.1.7 on 2021-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
