# Generated by Django 3.1.7 on 2021-04-07 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_consult_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patient'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
