# Generated by Django 3.1.7 on 2021-04-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210406_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
