# Generated by Django 3.1.7 on 2021-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210407_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
