# Generated by Django 3.1.7 on 2021-04-13 01:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210407_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
