# Generated by Django 3.1.7 on 2021-04-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210412_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
